---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

# Install GitLab and its dependencies.
- name: Install GitLab dependencies.
  package: name={{ item }} state=installed
  with_items:
    - openssh-server
    - postfix
    - curl
    - openssl
    - tzdata
  become: true

- name: Download GitLab repository installation script.
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
    validate_certs: "{{ gitlab_download_validate_certs }}"
  when: (gitlab_file.stat.exists == false)

- name: Install GitLab repository
  command: bash /tmp/gitlab_install_repository.sh
  when: (gitlab_file.stat.exists == false)
  become: true

- name: Define the Gitlab package name.
  set_fact:
    gitlab_package_name: "{{ gitlab_edition }}{{ gitlab_package_version_separator }}{{ gitlab_version }}"
  when: gitlab_version != ''

- name: Install GitLab
  package:
    name: "{{ gitlab_package_name | default(gitlab_edition) }}"
    state: installed
  when: (gitlab_file.stat.exists == false)
  become: true

- name: Create GitLab SSL configuration folder.
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700
  when: gitlab_create_self_signed_cert
  become: true

- name: Create self-signed certificate.
  command: >
    openssl req -new -nodes -x509 -subj "{{ gitlab_self_signed_cert_subj }}" -days 3650 -keyout {{ gitlab_ssl_certificate_key }} -out {{ gitlab_ssl_certificate }} -extensions v3_ca
    creates={{ gitlab_ssl_certificate }}
  when: gitlab_create_self_signed_cert
  become: true

- name: Copy GitLab configuration file.
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab
  become: true

# Start and configure GitLab. Sometimes the first run fails, but after that,
# restarts fix problems, so ignore failures on this run.
- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false
  become: true

# Make sure nfs-common is installed
- name: Ensure NFS common is installed
  package:
    name: nfs-common
    state: present
  become: true
  when: gitlab_high_availability

# Mount NFS shares for High Availability
- name: Mount all nfs shares
  mount: name="{{ item.mountpoint }}" src="{{ item.source }}" fstype=nfs opts=rsize=8192,wsize=8192,timeo=14,intr dump=0 passno=2 state=mounted
  with_items:
    - { mountpoint: "/var/opt/gitlab/git-data", source: "{{ gitlab_nfs_host }}:/export/git" }
    - { mountpoint: "/var/opt/gitlab/.ssh", source: "{{ gitlab_nfs_host }}:/export/ssh" }
    - { mountpoint: "/var/opt/gitlab-rails/uploads", source: "{{ gitlab_nfs_host }}:/export/uploads" }
    - { mountpoint: "/var/opt/gitlab-rails/shared", source: "{{ gitlab_nfs_host }}:/export/shared" }
    - { mountpoint: "/var/opt/gitlab-ci/builds", source: "{{ gitlab_nfs_host }}:/export/builds" }
    - { mountpoint: "/var/opt/gitlab/backups", source: "{{ gitlab_nfs_host }}:/export/backups" }
  become: true
  when: gitlab_high_availability


# Include master/slave configurations
- include: "{{ gitlabha_role }}.yml"
  when: gitlabha_role != 'skip'
  become: true
