---

- name: copy secrets file from master
  copy:
    src: /tmp/{{ groups.gitlab[0] }}/etc/gitlab/gitlab-secrets.json
    dest: /etc/gitlab/gitlab-secrets.json
  become: true
  register: secrets_copied

- name: add skip-auto-migrations on slave
  file:
    path: /etc/gitlab/skip-auto-migrations
    state: touch
  become: true

- name: Reconfigure GitLab (Secrets arrived).
  command: gitlab-ctl reconfigure
  when: secrets_copied

- name: copy ssh keys from master
  copy:
    src: /tmp/{{ groups.gitlab[0] }}/etc/ssh/{{ item }}
    dest: /etc/ssh/{{ item }}
  become: true
  notify: ssh restart
  with_items:
    - ssh_host_dsa_key
    - ssh_host_dsa_key.pub
    - ssh_host_ecdsa_key
    - ssh_host_ecdsa_key.pub
    - ssh_host_ed25519_key
    - ssh_host_ed25519_key.pub
    - ssh_host_rsa_key
    - ssh_host_rsa_key.pub
